// components/ArrowPuzzle.tsx
'use client';

import { useEffect, useRef, useState } from 'react';
import type { ArrowPuzzleHandle, ArrowPuzzleParams } from '@/games/arrow-puzzle';

const DEFAULT_PARAMS: ArrowPuzzleParams = {
  cols: 12,
  rows: 9,
  arrowCount: 20,
  seed: 1,
};

export default function ArrowPuzzle() {
  const containerRef = useRef<HTMLDivElement>(null);
  const handleRef = useRef<ArrowPuzzleHandle | null>(null);

  const [params, setParams] = useState<ArrowPuzzleParams>(DEFAULT_PARAMS);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    (async () => {
      if (!containerRef.current) return;
      try {
        const mod = await import('@/games/arrow-puzzle');
        if (cancelled || !containerRef.current) return;

        handleRef.current = mod.initArrowPuzzle(containerRef.current, DEFAULT_PARAMS);
        setLoading(false);
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : 'Failed to load');
          setLoading(false);
        }
      }
    })();

    return () => {
      cancelled = true;
      handleRef.current?.destroy();
      handleRef.current = null;
    };
  }, []);

  const applyParams = (next: ArrowPuzzleParams) => {
    setParams(next);
    handleRef.current?.setParams(next);
  };

  const updateArrowCount = (value: number) =>
    applyParams({ ...params, arrowCount: value });

  const updateSeed = (value: number) =>
    applyParams({ ...params, seed: value });

  const newRandom = () =>
    applyParams({ ...params, seed: Math.floor(Math.random() * 99999) + 1 });

  const restart = () => handleRef.current?.setParams(params);

  return (
    <div className="arrow-puzzle">
      <div className="arrow-viewport" ref={containerRef}>
        {loading && (
          <div className="shader-loading">
            <span className="spinner" /> Loading…
          </div>
        )}
        {error && (
          <div className="shader-loading" style={{ color: '#ff2e88' }}>
            ⚠ {error}
          </div>
        )}
      </div>

      <div className="shader-controls">
        <div className="shader-controls-head">
          <h3>Puzzle Settings</h3>
          <button className="reset-btn" onClick={restart}>Restart</button>
        </div>

        <div className="slider-row">
          <div className="slider-label">
            <span>Arrows</span>
            <span className="slider-value">{params.arrowCount}</span>
          </div>
          <input
            type="range"
            min={8}
            max={40}
            step={1}
            value={params.arrowCount}
            onChange={(e) => updateArrowCount(parseInt(e.target.value))}
          />
        </div>

        <div className="slider-row">
          <div className="slider-label">
            <span>Seed</span>
            <span className="slider-value">{params.seed}</span>
          </div>
          <input
            type="range"
            min={1}
            max={9999}
            step={1}
            value={params.seed}
            onChange={(e) => updateSeed(parseInt(e.target.value))}
          />
        </div>

        <button className="play-btn" style={{ marginTop: 8 }} onClick={newRandom}>
          🎲 New Puzzle
        </button>

        <div className="arrow-hint">
          Tap an arrow to send it flying like a snake.
          <br />
          <span style={{ color: 'var(--muted)' }}>
            Its path must be clear in the arrow's direction.
          </span>
        </div>
      </div>

      {/* ⭐ Tech note — full width, dưới 2 cột */}
      <details className="battle-city-tech" open>
        <summary>
          <span className="tech-icon">⚙</span>
          Tech behind this demo
        </summary>

        <div className="tech-grid">
          <div className="tech-item">
            <div className="tech-name">Reverse Generation</div>
            <div className="tech-desc">
              Levels are generated by simulating the solution backwards —
              every puzzle is <strong>guaranteed solvable</strong> without
              running a solver pass.
            </div>
          </div>

          <div className="tech-item">
            <div className="tech-name">Seeded RNG (mulberry32)</div>
            <div className="tech-desc">
              Deterministic random generator — same seed always produces the
              same puzzle. Enables sharing levels via URL or seed number.
            </div>
          </div>

          <div className="tech-item">
            <div className="tech-name">Snake Movement</div>
            <div className="tech-desc">
              Arrows fly off the grid like a snake: head leads the way and
              segments follow via a fixed-distance trail, preserving shape
              during flight.
            </div>
          </div>

          <div className="tech-item">
            <div className="tech-name">Path Validation</div>
            <div className="tech-desc">
              Generation validates each arrow's exit path is clear at placement
              time. No solver = no wasted CPU cycles for the player.
            </div>
          </div>

          <div className="tech-item">
            <div className="tech-name">Polyline Rendering</div>
            <div className="tech-desc">
              Each arrow is a densified polyline (2.5px per sample) with round
              joint interpolation and smoothed corners for fluid motion.
            </div>
          </div>

          <div className="tech-item">
            <div className="tech-name">Blocked Feedback</div>
            <div className="tech-desc">
              When blocked, the arrow head pushes toward the obstacle, flashes
              red, and snaps back — a tactile "try but can't" visual cue.
            </div>
          </div>
        </div>
      </details>
    </div>
  );
}